name: yuwen

services:
  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    command:
      - --wait_timeout=28800
      - --interactive_timeout=28800
      - --max_allowed_packet=32M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --default-time-zone=+8:00
      - --bind-address=0.0.0.0
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      yuwen_net:
        aliases:
          - mysql.yuwen.net
    healthcheck:
      test: ["CMD", "mysql", "-h", "127.0.0.1", "-P", "3306", "-u", "yuwen", "-pyuwen123", "-e", "SELECT 1;"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  yuwen:
    image: registry.cn-hangzhou.aliyuncs.com/mini_program/tingxie:latest
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - FLASK_DEBUG=1
      - DATA_DIR=/app/data
      - TZ=Asia/Shanghai
      - ALIBABA_CLOUD_ECS_METADATA=${ALIBABA_CLOUD_ECS_METADATA:-false}
    volumes:
      - .:/app
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      yuwen_net:
        aliases:
          - yuwen.yuwen.net
    command: >
      bash -c "
      sleep 10 &&
      gunicorn
      --bind 0.0.0.0:5000
      --workers 4
      --timeout 120
      --reload
      --access-logfile -
      --error-logfile -
      wsgi:app"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:6.2
    command: redis-server --appendonly yes
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      yuwen_net:
        aliases:
          - redis.yuwen.net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
      - LOG_LEVEL=info
    command: gunicorn -c gunicorn.conf.py wsgi:app

networks:
  yuwen_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  mysql_data:
  redis_data: 