class YuwenItem(BaseModel):
    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(32), nullable=False)
    pinyin = db.Column(db.String(32))
    explanation = db.Column(db.String(256))
    grade = db.Column(db.Integer, nullable=False)
    semester = db.Column(db.Integer, nullable=False)
    lesson = db.Column(db.Integer)
    lesson_name = db.Column(db.String(32))
    textbook_version = db.Column(db.String(32))
    audio_url = db.Column(db.String(256)) 